user: Пользователь
user.shape: person
user <-> ui: |md
  взаимодействует с ПИ 
  для решения задачи
|
ui: {
  explanation: |md
    ### пользовательский интерфейс
    - позволяет пользователю визуализировать и редактировать знания системы
    - конфигурируется системой под задачу, решаемую пользователем и системой
      - уровень опыта взаимодействия у пользователя
      - реализует подходящую модальность
      - предлагает выполнить (или автоматизировать) 
        
        те действия, что вероятно нужны пользователю
    - bruh
  |
}
sc-machine: {
  explanation: |md
    - содержит все знания, необходмые для решения задачи
    - исполняет алгоритмы решения задач
    - конфигурирует ПИ
  |
}
ui -> sc-память: редактирование знаний
sc-память <-> ui: запрос знаний
sc-память -> ui: обновление ПИ в соответствии\nс sc-моделью ПИ

