vars: {
  d2-config: {
    layout-engine: elk
  }
}
user: Пользователь
user.shape: person
system: ostis-система {
  ui: пользовательский интерфейс
  sc-machine: {
    kb: База знаний {
      ui-model: sc-модель ПИ
      kb-task: ПрО задачи
      kb-user: знания о пользователе
      kb-other: ...
      ui-components: ПрО компонентов ПИ
    }
    ps: Решатель задач {
      task-agents: агенты решения задач
      ui-agents: Модуль ПИ
      other: ...
    }
    _.ui -> kb: редактирование знаний
    kb -> _.ui: визуализация знаний
    kb -> ps: вызов агентов
    ps -> kb: использование знаний системы
    ps.task-agents -> kb: результаты решения задач
    ps.ui-agents -> kb.ui-model: обновлённая модель ПИ
    kb.ui-model -> _.ui: Обновление реализации ПИ
    kb.kb-user -> ps.ui-agents
    kb.ui-components -> ps.ui-agents
  }
}
user <-> system.ui: |md
  взаимодействует с системой 
  для решения задачи
|

