interaction-sequence-containers: Диаграмма последовательности интерпретации действия пользователя и обновления sc-модели ПИ {
  shape: sequence_diagram
  user
  ui
  web-server
  sc-memory
  UpdateModelAgent
  UIActionAgent
  Action
  web-server.s -> ui.s: изначальная разметка
  ui.s -> user.s
  user.s -> ui.s: нажатие на кнопку
  ui.s.reaction -> sc-memory: "создание конструкции действия\n[sc-json over WS]"
  sc-memory: {
    |md
      шаблон взаимодействия:
      addr компонента, 
      addr пользователя
      класс взаимодействия
      аргументы взаимодействия (если есть)
    |
  }
  sc-memory -> UIActionAgent.a
  UIActionAgent.a -> sc-memory: найти, какое действие нужно выполнить\nдля такого взаимодействия
  sc-memory -> UIActionAgent.a: шаблон действия
  UIActionAgent.a -> Action.a: запуск действия
  Action.a <-> sc-memory: чё-то происходит
  Action.a -> sc-memory: изменение модели ПИ (если необходимо)\nдобавление повторной трансляции изменённых\nкомпонентов в очередь\n(можно ли сделать реакцией на событие изменения?)
  Action.a -> UIActionAgent.a: действие завершено\n(в ответе может быть\nуведомление с текстом?)
  UIActionAgent.a -> UpdateModelAgent.u: действие завершено, надо обновить модель
  UpdateModelAgent.u -> sc-memory: вызываем агент шаблона для каждого из\n компонентов в очереди, разбуди,\nкогда завершится
  sc-memory -> templateAgent.t
  templateAgent.t -> sc-memory: обновлённые строки компонентов
  sc-memory -> UpdateModelAgent.u: Готово
  UpdateModelAgent.u -> sc-memory: Сформировать HTMX(?) сообщение\nсодержащее изменение разметки
  sc-memory -> web-server.s: Надо отослать SSE
  web-server.s -> ui: Отсылаем изменённую разметку
  ui.s -> user.s: ре-рендеринг
}
