interaction-sequence-containers: Диаграмма последовательности взаимодействия компонентов HTML-транслятора SC-модели ПИ {
  shape: sequence_diagram
  user
  web-server
  sc-memory.a
  setModelAgent
  adaptationAgent
  user -> web-server.get_page: запрос на получение ПИ
  web-server.get_page.get_model -> sc-memory.a: у пользователя есть\nустановленная модель ПИ?
  web-server.get_page.get_model <- sc-memory.a: нет
  web-server.get_page.get_model -> sc-memory.a: подписаться на появление интерпретируемой модели
  web-server.get_page.get_model.gen_model -> setModelAgent.get_model: Запрос на установку модели пользователю (inputs: user_info, current_task, ui_platform)
  gen-task-specific-model: {
    setModelAgent: {
      |md
        'Нет шаблона модели ПИ под задачку, надо её сгенерировать':
        Пока не поддерживаем этот сценарий, но будет 
        коллектив агентов генерации модели ПИ исходя
        из необходимых взаимодействий с пользователем
        (которые описаны в алгоритме решения задачи системы)
      |
    }
  }

  setModelAgent.get_model -> sc-memory.a: найти шаблон модели, которая решает задачу\n(ПрО интерфейсов ПИ)
  sc-memory.a -> setModelAgent.get_model: найдена
  setModelAgent.get_model -> sc-memory.a: заполнить шаблон модели ПИ\n(исходя из задачи, например шаблон модели ПИ\nдля задачи "Визуализировать, что такое 'x'?")\nсгенерировать конструкцию по шаблону\nи связать с пользователем
  sc-memory.a -> adaptationAgent.adapt_model: К пользователю привязана новая модель.\nАдаптируй.
  adaptationAgent.adapt_model -> sc-memory.a: найти:\nсаму модель ПИ\nзнания о контексте (устройство, внешняя среда)\nзнания о пользователе\nи правила для адаптации.
  adaptationAgent.adapt_model: {
    |md
      В правила адаптации входит стилизация, расположение и выбор
      среди альтернатив реализации класса компонента ПИ

      1. Отфильтровать правила 
        (оставить только применимые к среде, пользователю)
      2. Задать порядок применения правил (приоритезация правил), 
        т.к. могут быть альтернативные (взаимоисключающие) правила
        исходя из входной-выходной модели в правиле адаптации
      3. Применить правила преобразования модели
      4. На выходе - интерпретируемая, конкретная модель, с свойствами стиля
    |
  }
  adaptationAgent.adapt_model -> sc-memory.a: изменения модели, навесили класс интерпретируемости
  sc-memory.a -> web-server.get_page.get_model.gen_model: появилась интерпретируемая модель
  web-server.get_page -> sc-memory.a: а для этой модели может и разметка готовая?\n(поиск разметки для модели по хешу всех классов компонентов и их свойств,\nно пока непонятно как хешировать)
  sc-memory.a -> web-server.get_page.get_model: nope
  web-server.get_page -> sc-memory.a: какой агент отвечает за трансляцию в этой среде и для этой платформы?
  sc-memory.a -> web-server.get_page: вот соответствующее действие
  web-server.get_page.get_model -> sc-memory.a: подписаться на появление разметки для модели
  web-server.get_page.get_model -> HTMLTranslatorAgent.start_translation: протранслировать модель в разметку HTML
  HTMLTranslatorAgent.start_translation -> templateAgent.top_level: Заполнение шаблона для каждого компонента ПИ модели\n(вход - нода с классом компонента,\nк которой привязано правило трансляции)
  templateAgent.top_level -> templateAgent.top_level.lower_level: Рекурсивный вызов\n(в случае неатомарного компонента)
  templateAgent.top_level -> HTMLTranslatorAgent.start_translation: html-дерево компонентов
  HTMLTranslatorAgent.start_translation: {
    |md
      Добавление мета-тегов, нужных скриптов для 
      интерпретатора действий и используемых библиотек.
      Возможно это как-то надо формализовывать 
      эти зависимости в модели ПИ или
      в спецификации реализаций компонентов
    |
  }
  HTMLTranslatorAgent.start_translation -> sc-memory.a: Готовая HTML-строка
  sc-memory.a -> web-server.get_page: код страницы
  web-server.get_page -> user: Возврат страницы

  cache-hit: 1.1 кеширование трансляции (для часто используемых однотипных моделей) {
    web-server.check_hash -> sc-memory.a: акутальная разметка есть? А если найду?\n(sc-model hash == html page hash)?
    sc-memory.a -> web-server.check_hash: yes
    web-server.check_hash.search -> sc-memory.a: дай
    sc-memory.a -> web-server.check_hash.search: sc-ссылка с html
    web-server.check_hash -> user: страница
  }
  HTMLTranslatorAgent
  templateAgent
}
